/**
 * Ingredient Form and Display Helpers
 *
 * Utilities for guidance chips and brand/title formatting
 * NOTE: Ingredient forms are now handled by backend (ingredient_label field)
 */

// ============================================================================
// Brand/Title Formatting
// ============================================================================

/**
 * Check if product title already contains the brand name
 */
export function titleContainsBrand(title: string, brand: string): boolean {
  return title.toLowerCase().includes(brand.toLowerCase());
}

/**
 * Format product display name (brand · title)
 * Returns just title if title already contains brand
 */
export function formatProductName(title: string, brand: string): string {
  if (titleContainsBrand(title, brand)) {
    return title;
  }
  return `${brand} · ${title}`;
}

// ============================================================================
// Guidance Chips (Pre-Cart Trust Signals)
// ============================================================================

export interface GuidanceChip {
  label: string;
  tooltip: string;
  type: 'organic' | 'conventional' | 'fresh' | 'specialty';
}

/**
 * Get guidance chips for an ingredient based on category and properties
 * NOTE: These are contextual hints shown in ingredient confirmation modal ONLY
 * They should NOT duplicate information already shown in the form pill
 */
export function getIngredientGuidanceChips(
  ingredientName: string,
  ewgCategory: string | null,
  currentForm?: string | null
): GuidanceChip[] {
  const chips: GuidanceChip[] = [];
  const ingredientLower = ingredientName.toLowerCase();
  const formLower = currentForm?.toLowerCase();

  // EWG-based guidance (always show if applicable)
  if (ewgCategory === 'dirty_dozen') {
    chips.push({
      label: 'Organic recommended',
      tooltip: 'Organic recommended (EWG produce guidance)',
      type: 'organic',
    });
  } else if (ewgCategory === 'clean_fifteen') {
    chips.push({
      label: 'Conventional ok',
      tooltip: 'Conventional ok (lower residue category)',
      type: 'conventional',
    });
  }

  // Fresh ingredient guidance - ONLY if form is NOT already "fresh"
  const freshIngredients = ['ginger', 'garlic', 'mint', 'cilantro', 'basil', 'parsley'];
  if (freshIngredients.some(ing => ingredientLower.includes(ing)) && formLower !== 'fresh') {
    chips.push({
      label: 'Fresh preferred',
      tooltip: 'Fresh preferred for optimal flavor',
      type: 'fresh',
    });
  }

  // Specialty items
  const specialtyIngredients = ['cardamom', 'saffron', 'garam masala', 'ghee'];
  if (specialtyIngredients.some(ing => ingredientLower.includes(ing))) {
    chips.push({
      label: 'Specialty item',
      tooltip: 'Specialty item may ship later',
      type: 'specialty',
    });
  }

  return chips;
}

// ============================================================================
// Universal Chips Detection
// ============================================================================

/**
 * Detect universal chips that appear on most items
 * These should be moved to cart-level header instead of per-item
 */
export function detectUniversalChips(allChips: string[][]): Set<string> {
  const chipCounts = new Map<string, number>();
  const totalItems = allChips.length;

  // Count occurrences of each chip
  allChips.forEach(itemChips => {
    itemChips.forEach(chip => {
      chipCounts.set(chip, (chipCounts.get(chip) || 0) + 1);
    });
  });

  // A chip is "universal" if it appears on >80% of items
  const universalChips = new Set<string>();
  chipCounts.forEach((count, chip) => {
    if (count >= totalItems * 0.8) {
      universalChips.add(chip);
    }
  });

  return universalChips;
}

/**
 * Filter out universal chips from an item's chip list
 */
export function filterUniversalChips(chips: string[], universalChips: Set<string>): string[] {
  return chips.filter(chip => !universalChips.has(chip));
}

// ============================================================================
// Chip Text Sanitization
// ============================================================================

/**
 * Sanitize chip text to be more user-friendly
 */
export function sanitizeChipText(text: string): string {
  return text
    .replace(/No Active Recalls/gi, 'No recall signals found')
    .replace(/FDA recalls?/gi, 'Recent category recalls');
}

// ============================================================================
// NOTE: Reasons and tradeoffs are now generated by backend
// ============================================================================
// - reason_line: Single sentence explaining selection
// - reason_details: 1-2 bullets for ⓘ hover
// - chips.tradeoffs: Max 2 chips (from backend)
// Frontend no longer generates these - they come from API response
